# Generated by Django 3.1.6 on 2021-02-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('depart_from', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=80)),
                ('depart_timing', models.TimeField()),
                ('reach_timing', models.TimeField()),
                ('seats', models.IntegerField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
                ('date', models.DateField()),
            ],
        ),
    ]
