# Generated by Django 3.1.6 on 2021-02-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='flights',
            new_name='info',
        ),
    ]
